apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  annotations:
    my-own-ann: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
