apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
