apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  annotations:
    configmanagement.gke.io/managed: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
